import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Image from 'next/image'
import phone from '@/public/phone.png'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <div className="relative h-screen flex items-center justify-center">
        <div className="main-wrapper bg-cover bg-no-repeat bg-center relative">
          <Image
            src={phone}
            alt="Phone"
          />
    
          {children}
         
        </div>
      </div>
  )
}
